# theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Mario Hinterreiter
description: Digitalisierung f√ºr Bau, Handwerk und Industrie

show_downloads: false
# google_analytics: 123
